### ISSUE TITLE
codesearch-log appears to be undefined

### ISSUE THREAD

**Issue by makuto** [abingham/emacs-codesearch#12]
When I try to run codesearch I get an error involving "undefined symbol G33". If I do the following, the code works:
`(defun codesearch-log (severity format &rest args)
  )`

**Comment by abingham** [comment]
I've seen this, and deleting the elc file seems to make it go away. This is
not a very satisfactory answer, so I guess I should dig into this.

**Comment by abingham** [comment]
I poked at this a bit, but I can't replicate it now. What steps do you follow to get this to happen?

**Comment by abingham** [comment]
Ok, I've found out how to trigger this issue. I have to run `codesearch-build-index` and it seems to happen.

**Comment by abingham** [comment]
It seems that the call to `elog-open-log` simply isn't being called or having the necessary effect. I can trigger the bug you're seeing, but if I then go and execute that line explicitly, everything works fine.

I don't think I have the patience to dig into the elog macros and stuff. It's probably better to log use a different logging system. Or drop logging altogether if it turns out to be too much trouble.

**Comment by abingham** [comment]
I've replaced elog with log4e in f6eb96f034a925444412cfa03e45e0ccbbafe3f2. I guess it'll take a bit to get into melpa, but give it a try and let me know if it works for you. If so, please close this out. Thanks!

**Comment by makuto** [comment]
Awesome, thanks for the quick response! I'll check out tomorrow.

**Comment by makuto** [comment]
It appears to have gone away. Thanks!
